name: Publish to crates.io
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: CARGO_PUBLISH  # Optional: for enhanced security
    permissions:
      id-token: write     # Required for OIDC token exchange
    steps:
    - uses: actions/checkout@v5
    - uses: rust-lang/crates-io-auth-action@v1
      id: auth
    - run: cargo +1.90 publish --workspace
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
